version: '3.9'

services:
  web:
    build: .
    command: python /code/manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - 8000:8000

  db:
<<<<<<< HEAD
    image: postgres:16
=======
    image: postgres:15
>>>>>>> 4519580 (Add rest framework to requirements.txt)
    environment:
      - "POSTGRES_HOST_AUTH_METHOD=trust"
